services:
  - type: web
    name: semify-indexation-checker
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: SERPAPI_KEY
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_EMAIL
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_TRACKING_TAB
        value: "TRACKING- MAINTENANCE/REHAB"
      - key: NODE_ENV
        value: production
